### ISSUE TITLE
LICENSE does not agree with lib/Math/Utils.pm and README

### ISSUE THREAD

**Issue by jplesnik** [jgamble/Math-Utils#4]
Math-Utils-1.10 has weird license declaration. While generated LICENSE file quotes 'GPL+ or Artistic 1' license, lib/Math/Utils.pm and README files declares Artistic 2.0

In Build.PL, there should be license 'artistic_2' instead of 'perl' to generate correct LICENSE file.

**Comment by jgamble** [comment]
Other way around actually; all my modules have a license of 'perl'. It's the boiler text Module::Start generated that's in error (or my use of Module::Start).

Thanks, I'll fix/delete the text in question.

**Comment by jgamble** [comment]
And done, with version 1..11.

Thanks again.
